// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbxyar9MxI7RQ4l8KbDjBbWH15f03Q1Wc',
    appId: '1:688137699806:android:09fb31d7d0b4143f1f5d4f',
    messagingSenderId: '688137699806',
    projectId: 'ratio-calendar-f5a8f',
    storageBucket: 'ratio-calendar-f5a8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeFsrrJdHagvd2VnnU5oYK32j0A5h6X8g',
    appId: '1:688137699806:ios:ba6461a1ad8ca6df1f5d4f',
    messagingSenderId: '688137699806',
    projectId: 'ratio-calendar-f5a8f',
    storageBucket: 'ratio-calendar-f5a8f.firebasestorage.app',
    iosClientId: '688137699806-ulhd0jskfpmiehl2udiavm010tt1tr9g.apps.googleusercontent.com',
    iosBundleId: 'com.ratiocalendar.app',
  );
}
